name: Activity 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest # Setup OS (Linux)

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Python environment
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify Python version

    # 3. Install Python dependencies (including Behave)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install behave

    # 4. Run Behave tests
    - name: Run Behave tests
      run: |
        behave || echo "Tests failed, but continuing for reporting."

    # 5. Archive test results
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: behave-results
        path: reports/ # Ensure your Behave tests output reports here

    # 6. (Optional) Upload issue reports
    - name: Archive logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: logs/ # Replace with the actual log directory
        if-no-files-found: ignore

